// Static mock event data for UI development
// Replace the API call in events_api.js with this data to preview the UI without a running server.

const STATIC_EVENTS = [
    {
        external_id: "evt-001",
        title: "Bitcoin 2026 Global Summit",
        description: "The world's largest Bitcoin conference returns with top speakers, workshops, and networking opportunities for enthusiasts and professionals alike.",
        date_time: "2026-03-15T09:00:00Z",
        end_time: "2026-03-17T18:00:00Z",
        venue: "Miami Beach Convention Center, Miami, USA",
        organizer: "Bitcoin Magazine",
        category_tags: "conference,bitcoin,networking",
        image_url: "https://media.istockphoto.com/id/1370016371/photo/web3-world-wide-web-based-on-blockchain-incorporating-decentralization-and-token-based.jpg?s=612x612&w=0&k=20&c=gF2UzFFW0sfInYz00-obiuGUv2enz3C1gr1yfGOhfME=",
        ticket_url: "https://example.com/bitcoin-2026"
    },
    {
        external_id: "evt-002",
        title: "Ethereum DevConnect 2026",
        description: "A week-long gathering for Ethereum developers, researchers, and community members to collaborate on the future of the Ethereum ecosystem.",
        date_time: "2026-04-10T10:00:00Z",
        end_time: "2026-04-14T17:00:00Z",
        venue: "Pragati Maidan, New Delhi, India",
        organizer: "Ethereum Foundation",
        category_tags: "conference,ethereum,developer",
        image_url: "https://media.gettyimages.com/id/1499038790/photo/japanese-businessman-making-a-presentation-on-virtual-reality-and-metaverse.jpg?s=612x612&w=0&k=20&c=DPR6AGghBvBad2QMZNL5NOqbrk8b1adEn4PQu79Abns=",
        ticket_url: "https://example.com/eth-devconnect"
    },
    {
        external_id: "evt-003",
        title: "DeFi Hack-a-thon NYC",
        description: "48-hour hackathon focused on building the next generation of decentralized finance applications. Over $100K in prizes!",
        date_time: "2026-02-20T08:00:00Z",
        end_time: "2026-02-22T20:00:00Z",
        venue: "Brooklyn Navy Yard, New York, USA",
        organizer: "DeFi Alliance",
        category_tags: "hackathon,defi,developer",
        image_url: "https://media.istockphoto.com/id/1370016371/photo/web3-world-wide-web-based-on-blockchain-incorporating-decentralization-and-token-based.jpg?s=612x612&w=0&k=20&c=gF2UzFFW0sfInYz00-obiuGUv2enz3C1gr1yfGOhfME=",
        ticket_url: "https://example.com/defi-hack"
    },
    {
        external_id: "evt-004",
        title: "Web3 Women in Blockchain Meetup",
        description: "Monthly meetup celebrating and empowering women in the blockchain space. Talks, panels, and networking.",
        date_time: "2026-02-16T18:00:00Z",
        end_time: "2026-02-16T21:00:00Z",
        venue: "WeWork Whitefield, Bangalore, India",
        organizer: "Web3 Women DAO",
        category_tags: "meetup,community,networking",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/web3-women"
    },
    {
        external_id: "evt-005",
        title: "Solana Breakpoint 2026",
        description: "The flagship Solana conference bringing together builders, creators, and visionaries to showcase the latest innovations on the Solana blockchain.",
        date_time: "2026-05-05T09:00:00Z",
        end_time: "2026-05-07T18:00:00Z",
        venue: "Suntec Convention Centre, Singapore",
        organizer: "Solana Foundation",
        category_tags: "conference,solana,developer",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/solana-breakpoint"
    },
    {
        external_id: "evt-006",
        title: "NFT Art Exhibition — Digital Horizons",
        description: "Immersive art exhibition showcasing NFT artworks from 50+ digital artists. Live minting events and artist meet-and-greets.",
        date_time: "2026-02-10T11:00:00Z",
        end_time: "2026-02-12T20:00:00Z",
        venue: "Saatchi Gallery, London, UK",
        organizer: "CryptoArt Collective",
        category_tags: "exhibition,nft,art",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/nft-exhibition"
    },
    {
        external_id: "evt-007",
        title: "Crypto Regulatory Roundtable",
        description: "Leading legal experts and policymakers discuss the evolving regulatory landscape for digital assets and blockchain technology.",
        date_time: "2026-03-01T14:00:00Z",
        end_time: "2026-03-01T17:00:00Z",
        venue: "The Ritz-Carlton, Washington D.C., USA",
        organizer: "Blockchain Policy Institute",
        category_tags: "conference,regulation,policy",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/crypto-regulation"
    },
    {
        external_id: "evt-008",
        title: "Layer 2 Scaling Summit",
        description: "Deep dive into Layer 2 solutions — rollups, sidechains, and state channels. Featuring technical workshops and protocol demos.",
        date_time: "2026-04-22T09:00:00Z",
        end_time: "2026-04-23T17:00:00Z",
        venue: "Station F, Paris, France",
        organizer: "L2Beat",
        category_tags: "conference,layer2,developer,workshop",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/l2-summit"
    },
    {
        external_id: "evt-009",
        title: "DAO Governance Workshop",
        description: "Hands-on workshop covering DAO frameworks, governance models, and tooling. Build and deploy your own DAO in a day.",
        date_time: "2026-02-14T10:00:00Z",
        end_time: "2026-02-14T16:00:00Z",
        venue: "IIM Bangalore, Bangalore, India",
        organizer: "DAOhaus",
        category_tags: "workshop,dao,governance",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/dao-workshop"
    },
    {
        external_id: "evt-010",
        title: "Consensus 2026",
        description: "CoinDesk's annual flagship event — the most influential gathering in crypto, blockchain, and Web3.",
        date_time: "2026-06-10T08:00:00Z",
        end_time: "2026-06-12T18:00:00Z",
        venue: "Austin Convention Center, Austin, USA",
        organizer: "CoinDesk",
        category_tags: "conference,networking,web3",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/consensus-2026"
    },
    {
        external_id: "evt-011",
        title: "Zero Knowledge Proof Bootcamp",
        description: "Intensive 3-day bootcamp on ZK proofs — learn zk-SNARKs, zk-STARKs, and how to build privacy-preserving applications.",
        date_time: "2026-03-20T09:00:00Z",
        end_time: "2026-03-22T17:00:00Z",
        venue: "MIT Media Lab, Cambridge, USA",
        organizer: "ZK Academy",
        category_tags: "workshop,zk-proofs,developer",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/zk-bootcamp"
    },
    {
        external_id: "evt-012",
        title: "Crypto Traders Meetup — Delhi NCR",
        description: "Casual networking event for crypto traders. Share strategies, discuss market trends, and connect with fellow traders.",
        date_time: "2026-02-15T17:00:00Z",
        end_time: "2026-02-15T20:00:00Z",
        venue: "Connaught Place, New Delhi, India",
        organizer: "Delhi Crypto Club",
        category_tags: "meetup,trading,networking",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/delhi-traders"
    },
    {
        external_id: "evt-013",
        title: "Polkadot Decoded 2026",
        description: "Discover the latest developments in the Polkadot ecosystem. Talks from parachain teams, runtime developers, and governance experts.",
        date_time: "2026-07-01T09:00:00Z",
        end_time: "2026-07-02T18:00:00Z",
        venue: "Messe Berlin, Berlin, Germany",
        organizer: "Web3 Foundation",
        category_tags: "conference,polkadot,developer",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/polkadot-decoded"
    },
    {
        external_id: "evt-014",
        title: "GameFi & Metaverse Expo",
        description: "Explore the intersection of gaming and blockchain. Demo the latest play-to-earn games, metaverse environments, and virtual economies.",
        date_time: "2026-05-20T10:00:00Z",
        end_time: "2026-05-22T19:00:00Z",
        venue: "COEX Convention Center, Seoul, South Korea",
        organizer: "GameFi Guild",
        category_tags: "exhibition,gamefi,metaverse",
        image_url: "https://static.vecteezy.com/system/resources/thumbnails/013/443/648/small/metaverse-and-blockchain-technology-concepts-person-with-an-experiences-of-metaverse-virtual-world-via-smart-phone-futuristic-tone-conceptual-photo.jpg",
        ticket_url: "https://example.com/gamefi-expo"
    },
    {
        external_id: "evt-015",
        title: "Blockchain for Social Impact Forum",
        description: "How blockchain technology is solving real-world problems — financial inclusion, supply chain transparency, and digital identity.",
        date_time: "2026-04-05T09:00:00Z",
        end_time: "2026-04-05T17:00:00Z",
        venue: "United Nations Conference Centre, Nairobi, Kenya",
        organizer: "Blockchain for Good",
        category_tags: "conference,social-impact,community",
        image_url: "https://media.gettyimages.com/id/1401952884/photo/pixelated-people-walking-the-streets.jpg?s=612x612&w=0&k=20&c=4Xr5I_HmMlepYxpaFKDhONJH2Yk65MGiFr7fz2oxBPA=",
        ticket_url: "https://example.com/blockchain-social"
    },
    {
        external_id: "evt-016",
        title: "Stablecoin Summit Dubai",
        description: "Leading stablecoin issuers, regulators, and DeFi builders discuss the future of digital dollars and programmable money.",
        date_time: "2026-03-28T09:00:00Z",
        end_time: "2026-03-29T17:00:00Z",
        venue: "Atlantis The Royal, Dubai, UAE",
        organizer: "Stablecoin Alliance",
        category_tags: "conference,stablecoin,defi",
        image_url: "https://media.gettyimages.com/id/2148123501/photo/big-data-structure-blocks-concept.jpg?s=612x612&w=0&k=20&c=PlEqZm4p-LB6Y6WbVNJigy7LyM9uxZVGO67rC_XI0a4=",
        ticket_url: "https://example.com/stablecoin-summit"
    }
];
